export const WAPII_SAVE_PERMISSIONS = "WAPII_SAVE_PERMISSIONS";
export const WAPII_SAVE_AUTHORIZED_APPS = "WAPII_SAVE_AUTHORIZED_APPS";
export const WAPII_UPDATE_IDENTITY = "WAPII_UPDATE_IDENTITY";
export const WAPII_SAVE_ACCOUNTS = "WAPII_SAVE_ACCOUNTS";